import { CheckCircle2, Cloud, Search, ShieldCheck, TriangleAlert } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";
import { API_URL } from "../../../lib/api";

type AzureStatus={provider:string;configured:boolean;region:string;rawAudioStored:boolean};
type Assessment={id:string;email:string;promptId:string;promptTitle:string;provider:string;assessmentStatus:string;recognizedText:string;referenceText:string;responseAppropriate:boolean;contextVerdict:string;contextExplanation:string;pronunciationFeedback:string;pronunciationGuide:string;pronunciationScore:number;accuracyScore:number;fluencyScore:number;completenessScore:number;feedback:string;wordIssues:string[];assessedAt:string};

export default function AdminDialogueRelayPage(){
  const [status,setStatus]=useState<AzureStatus|null>(null),[email,setEmail]=useState(""),[items,setItems]=useState<Assessment[]>([]),[message,setMessage]=useState("");
  useEffect(()=>{void fetch(`${API_URL}/api/dialogue-relay/bonus/status`).then(async response=>{if(!response.ok)throw new Error();setStatus(await response.json());}).catch(()=>setStatus({provider:"AZURE_SPEECH",configured:false,region:"unknown",rawAudioStored:false}));},[]);
  const lookup=async(event:FormEvent)=>{event.preventDefault();setMessage("Loading Azure assessments…");setItems([]);try{const response=await fetch(`${API_URL}/api/dialogue-relay/bonus/assessments?email=${encodeURIComponent(email.trim())}`);if(!response.ok)throw new Error();const data=await response.json() as Assessment[];setItems(data);setMessage(data.length?"":"No Dialogue Relay bonus assessment is recorded for this learner.");}catch{setMessage("Assessment history could not be loaded.");}};
  return <section className="response-admin-page"><header><div className="response-page-icon relay"><Cloud/></div><div><small>QUACKRESPONSE · SPEAKING BONUS</small><h1>Dialogue Relay</h1><p>Verify Azure scans and review returned speech scores. Microphone recordings are never retained.</p></div><div className={`azure-status ${status?.configured?'ready':'missing'}`}>{status?.configured?<CheckCircle2/>:<TriangleAlert/>}<div><b>{status?.configured?'Azure connected':'Azure configuration missing'}</b><span>{status?.configured?`${status.provider} · ${status.region}`:'Redeploy Render after adding the Speech key.'}</span></div></div></header><div className="audio-privacy-note"><ShieldCheck/><div><b>Scores and transcripts only</b><span>Each successful row is marked SCANNED. Raw learner audio is converted temporarily for Azure and deleted immediately afterward.</span></div></div><form className="response-lookup" onSubmit={lookup}><Search/><input type="email" required value={email} onChange={event=>setEmail(event.target.value)} placeholder="Learner email address"/><button>Find assessments</button></form>{message&&<p className="response-admin-message">{message}</p>}<div className="assessment-list">{items.map(item=><article key={item.id} className="assessment-card"><div className="assessment-top"><div><span className="scan-pill"><CheckCircle2/> {item.assessmentStatus||'SCANNED'}</span><small>{item.promptTitle} · {new Date(item.assessedAt).toLocaleString()}</small></div><b className={item.responseAppropriate?'fit':'retry'}>{item.contextVerdict?.replaceAll('_',' ')||'ASSESSED'}</b></div><div className="assessment-speech"><small>AZURE HEARD</small><strong>{item.recognizedText||'No clear transcription'}</strong><span>Model response: {item.referenceText}</span><span>Guide: {item.pronunciationGuide}</span></div><div className="assessment-scores"><Score label="Pronunciation" value={item.pronunciationScore}/><Score label="Accuracy" value={item.accuracyScore}/><Score label="Fluency" value={item.fluencyScore}/><Score label="Completeness" value={item.completenessScore}/></div><p><b>Situation:</b> {item.contextExplanation||item.feedback}</p><p><b>Pronunciation:</b> {item.pronunciationFeedback}</p>{item.wordIssues?.length>0&&<small className="word-issues">Review: {item.wordIssues.join(' · ')}</small>}</article>)}</div></section>;
}
function Score({label,value}:{label:string;value:number}){return <div><b>{Math.round(value||0)}</b><span>{label}</span></div>}
