import { ArrowLeft, ArrowRight, BookOpen, Check, Clock3, FileText, HelpCircle, Plus, Sparkles, Trash2, Upload } from "lucide-react";
import { useEffect, useState } from "react";
import { Link, useNavigate, useSearchParams } from "react-router-dom";
import StatusMessage from "../components/StatusMessage";
import { teacherApi } from "../services/teacherApi";
import type { ClassRecord, Lesson } from "../types";

type Question=NonNullable<Lesson["quiz"]>[number];
const emptyQuestion=():Question=>({prompt:"",type:"MULTIPLE_CHOICE",choices:["","","",""],correctAnswer:"",explanation:""});
export default function CreateLessonPage(){
 const [params]=useSearchParams(); const navigate=useNavigate(); const [step,setStep]=useState(0); const [classes,setClasses]=useState<ClassRecord[]>([]); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
 const initialClass=params.get("class")||""; const [classIds,setClassIds]=useState<string[]>(initialClass?[initialClass]:[]); const [title,setTitle]=useState(""); const [type,setType]=useState("WORDS"); const [description,setDescription]=useState(""); const [content,setContent]=useState(""); const [pdf,setPdf]=useState<File|null>(null); const [quiz,setQuiz]=useState<Question[]>([]); const [timed,setTimed]=useState(false); const [minutes,setMinutes]=useState(5);
 useEffect(()=>{teacherApi.getClasses().then(data=>{setClasses(data);setClassIds(current=>current.length?current:data[0]?[data[0].classCodes]:[])}).catch(e=>setError(e.message))},[]);
 const update=(index:number,patch:Partial<Question>)=>setQuiz(items=>items.map((q,i)=>i===index?{...q,...patch}:q));
 const validateStep=()=>{if(step===0&&(!classIds.length||!title.trim())){setError("Choose at least one class section and add a lesson title.");return false}if(step===1&&!pdf&&!content.trim()){setError("Upload a readable PDF or add lesson text.");return false}setError("");return true};
 const next=()=>{if(validateStep())setStep(value=>Math.min(2,value+1))};
 const save=async()=>{if(busy||!validateStep())return;setBusy(true);setError("");try{const sections=content.trim()?content.split(/\n\s*\n/).filter(Boolean).map((body,index)=>({heading:index===0?title:`Lesson note ${index+1}`,body:body.trim()})):[];const lesson=await teacherApi.createTeacherLesson({classId:classIds[0],classIds,lesson_title:title.trim(),lesson_type:type,lesson_description:description.trim(),sections,quiz:quiz.filter(q=>q.prompt.trim()),quizTimerSeconds:timed?minutes*60:null,published:true},pdf);navigate(`/teacher/lessons/${lesson.id}`)}catch(e){setError(e instanceof Error?e.message:"Lesson could not be created.")}finally{setBusy(false)}};
 return <section className="lesson-builder-page"><Link className="back-inline" to="/teacher/lessons"><ArrowLeft/>Back to lessons</Link>
  <div className="lesson-builder-head"><div><span className="eyebrow">NEW CLASS LESSON</span><h2>Build a lesson milestone</h2><p>Turn your notes or PDF into readable lesson cards, then add an optional knowledge check.</p></div><span>Step {step+1} of 3</span></div>
  <nav className="lesson-builder-steps">{[[BookOpen,"Lesson setup"],[FileText,"Learning content"],[Sparkles,"Quiz & publish"]].map(([Icon,label],index)=>{const I=Icon as typeof BookOpen;return <button className={step===index?"active":step>index?"done":""} onClick={()=>index<step&&setStep(index)} key={label as string}><span>{step>index?<Check/>:<I/>}</span><b>{label as string}</b></button>})}</nav>
  {error&&<StatusMessage>{error}</StatusMessage>}
  <div className="lesson-builder-card">
   {step===0&&<div className="lesson-builder-form"><div className="builder-intro"><BookOpen/><div><h3>Set up the milestone</h3><p>This information becomes the new lesson container students see.</p></div></div><fieldset className="lesson-class-picker"><legend>Assign to class sections</legend><p>Select one or more sections. Every enrolled learner in those sections receives the same lesson.</p><div>{classes.map(c=>{const selected=classIds.includes(c.classCodes);return <button type="button" aria-pressed={selected} className={selected?"selected":""} onClick={()=>setClassIds(items=>selected?items.filter(code=>code!==c.classCodes):[...items,c.classCodes])} key={c.classCodes}><span>{selected?<Check/>:<Plus/>}</span><b>{c.classCodes}</b><small>{selected?"Assigned":"Select section"}</small></button>})}</div><small>{classIds.length} section{classIds.length===1?"":"s"} selected</small></fieldset><label>Lesson title<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="e.g. Useful phrases at a restaurant"/></label><label>Learning path<select value={type} onChange={e=>setType(e.target.value)}><option value="KANA">Kana</option><option value="WORDS">Words</option><option value="GRAMMAR">Grammar</option><option value="ENRICHMENT">Enrichment</option></select></label><label>Short introduction<textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Tell learners what they will be able to do."/></label></div>}
   {step===1&&<div className="lesson-builder-form"><div className="builder-intro"><FileText/><div><h3>Add the learning material</h3><p>A text-based PDF is extracted into lesson cards. The original PDF is not shown as the lesson.</p></div></div><label className="pdf-drop"><Upload/><b>{pdf?pdf.name:"Choose a PDF"}</b><small>Text-based PDF · up to 10 MB</small><input type="file" accept="application/pdf" onChange={e=>setPdf(e.target.files?.[0]||null)}/></label><div className="builder-divider"><span>OR ADD TEXT MANUALLY</span></div><label>Lesson notes<textarea className="lesson-content-input" value={content} onChange={e=>setContent(e.target.value)} placeholder="Separate sections with a blank line. Each section becomes a learner-friendly content card."/></label></div>}
   {step===2&&<div className="lesson-builder-form"><div className="builder-intro"><Sparkles/><div><h3>Optional lesson quiz</h3><p>Add different question types. The student’s latest, average, and highest results are saved for your reports.</p></div></div><div className="quiz-timer-row"><label><input type="checkbox" checked={timed} onChange={e=>setTimed(e.target.checked)}/>Use a quiz timer</label>{timed&&<label><Clock3/>Minutes<input type="number" min="1" max="120" value={minutes} onChange={e=>setMinutes(Number(e.target.value))}/></label>}</div><div className="quiz-question-list">{quiz.map((q,index)=><article key={index}><header><b>Question {index+1}</b><button onClick={()=>setQuiz(items=>items.filter((_,i)=>i!==index))}><Trash2/></button></header><label>Question or prompt<input value={q.prompt} onChange={e=>update(index,{prompt:e.target.value})}/></label><label>Answer type<select value={q.type} onChange={e=>update(index,{type:e.target.value as Question["type"],choices:e.target.value==="TRUE_FALSE"?["True","False"]:q.choices})}><option value="MULTIPLE_CHOICE">Multiple choice</option><option value="TRUE_FALSE">True or false</option><option value="FILL_BLANK">Fill in the blank</option><option value="IDENTIFICATION">Identification</option></select></label>{q.type==="MULTIPLE_CHOICE"&&<div className="choice-grid">{q.choices.map((choice,i)=><label key={i}>Choice {String.fromCharCode(65+i)}<input value={choice} onChange={e=>{const choices=[...q.choices];choices[i]=e.target.value;update(index,{choices})}}/></label>)}</div>}<label>Correct answer{q.type==="TRUE_FALSE"?<select value={q.correctAnswer} onChange={e=>update(index,{correctAnswer:e.target.value})}><option value="">Choose answer</option><option>True</option><option>False</option></select>:<input value={q.correctAnswer} onChange={e=>update(index,{correctAnswer:e.target.value})} placeholder={q.type==="MULTIPLE_CHOICE"?"Must match one choice exactly":"Expected answer"}/>}</label><label>Explanation after answering<input value={q.explanation} onChange={e=>update(index,{explanation:e.target.value})} placeholder="Explain why this answer is correct."/></label></article>)}</div><button className="add-quiz-question" onClick={()=>setQuiz(items=>[...items,emptyQuestion()])}><Plus/>Add question</button>{!quiz.length&&<div className="quiz-optional-note"><HelpCircle/><span><b>A quiz is optional</b><small>You may publish this as a reading-only lesson.</small></span></div>}</div>}
   <footer className="lesson-builder-actions"><button className="soft-button" disabled={step===0||busy} onClick={()=>setStep(v=>v-1)}><ArrowLeft/>Back</button>{step<2?<button className="primary-button" onClick={next}>Continue<ArrowRight/></button>:<button className="primary-button" disabled={busy} onClick={()=>void save()}>{busy?"Creating lesson…":"Publish lesson"}<Check/></button>}</footer>
  </div>
 </section>
}
